### ISSUE TITLE
The basic example with the image (png) generation does not work even the .zip too

### ISSUE THREAD

**Issue by Saint-Cyr** [hackzilla/BarcodeBundle#11]
`public function indexAction()
    {
       
        return $this->getBarCodeAction('2344243');
        
        //return $this->render('KmBundle:Default:index.html.twig');
    }
    
    public function getBarCodeAction($code)
    {
        $barcode = $this->get('hackzilla_barcode');
        $barcode->setMode(Barcode::MODE_PNG);

        $headers = array(
            'Content-Type' => 'image/png',
            'Content-Disposition' => 'inline; filename="'.$code.'.png"'
        );
        
        return new Response($barcode->outputImage($code), 200, $headers);
    }`

generate this 500 error: Warning: imagepng() expects parameter 1 to be resource, null given

Stack Trace:
in vendor/hackzilla/barcode-bundle/Utility/Barcode.php at line 284   -
    public function outputPng($code)
    {
        $im = $this->returnImage($code);
        \imagepng($im);
    }
    /**

Environment: Symfony 3.1.2

**Comment by hackzilla** [comment]
Can you tell me what version of php and gd lib you have?

**Comment by Saint-Cyr** [comment]
`php -version
PHP 5.6.4-4ubuntu6.4 (cli) (built: Oct 28 2015 01:26:54) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.6, Copyright (c) 2002-2014, by Derick Rethans
    with blackfire v1.10.0, https://blackfire.io, by Blackfireio Inc.
`
`sudo apt-get install php5-gd` -  successfully installation but same error: Warning: imagepng() expects parameter 1 to be resource, null given

**Comment by hackzilla** [comment]
I've had a look and I believe its because you aren't passing in a value barcode (ean 10/13).

You should have had a message outputted:

```
BarcodeBundle needs an external programm for encodings other then EAN/ISBN
download gnu-barcode from www.gnu.org/software/barcode/
compile and install them
download genbarcode from www.ashberg.de/php-barcode/
compile and install them
specify path to genbarcode in php-barcode.php

Folke Ashberg's OpenSource PHP-Barcode
```

This is because it doesn't understand the code ```2344243```.

Try

```
        $code = '9781477849965';
```

I really should be using exceptions to make this a lot easier to detect, but the whole library needs a refactor.

**Comment by Saint-Cyr** [comment]
Thank you !

**Comment by etmind** [comment]
I got error from example barcodeImageAction Undefined class constant 'MODE_PNG'

**Comment by hackzilla** [comment]
You'll need to add a use statement for the Barcode class.

```
use Hackzilla\BarcodeBundle\Utility\Barcode;
```
