### ISSUE TITLE
multiple barcode png into a single template

### ISSUE THREAD

**Issue by Falar81** [hackzilla/BarcodeBundle#6]
Hi,
How do I include multiple barcode png into a single twig template?

thank you so much.

**Comment by hackzilla** [comment]
I'm not sure on what you're trying to achieve, but I'd save the images in the controller, and pass a array of filenames into your twig template

**Comment by hackzilla** [comment]
look at [Return image in a zip](https://github.com/hackzilla/BarcodeBundle/blob/master/Resources/doc/example.md)

from the example
```
        foreach ($isbns as $i => $isbn) {
            $barcode = \trim($isbn);
            $zip->addFromString($barcode . '.png', $this->getImage($barcode));
        }
```

would become
```
        $images = [];
        foreach ($isbns as $i => $isbn) {
            $barcode = \trim($isbn);
            $filename = '/img/'.$barcode.'.png';
            $images[] += $filename;
            file_put_contents($filename, $this->getImage($barcode));
        }

        return $this->render('template', ['barcodes' => $images]);
```

**Comment by Falar81** [comment]
how can I print these codes in a single PDF without saving the images on my hard drive?

**Comment by hackzilla** [comment]
yeah, the html output won't be saving the files anywhere.

So it'd be more efficient in the long run.
