### ISSUE TITLE
Remove need for twig

### ISSUE THREAD

**Issue by garygreen** [hackzilla/BarcodeBundle#7]
Atm if you want to output HTML barcode you need to install twig or install this in a Symphony app, which is a bit of a pain considering that this package is only outputting very basic HTML.

Everything works great using this outside of Symphony except html outputting. Could the views not be changed to just just raw PHP?

**Comment by hackzilla** [comment]
This makes a lot of sense.

The reason I used twig was for including other templates, and assets easily.

Assets is the tricker one of the two, because I can't guess what the url is to display the required images.
However this could be set with method.

The other alternative is to use css.

**Comment by hackzilla** [comment]
Doing this would also solve #5

**Comment by garygreen** [comment]
Yeah. I mean twig is good and I realise this is mainly a Symphony "bundle" package but personally I'm using this outside of symphony and its great. Just need to remove the dependency if possible as the twig views are so simple.

The black / white bar images could be css like you say, maybe even just a simple base64 encoded version in the css that way you don't need to worry about paths at all.

**Comment by hackzilla** [comment]
I've got a rough version in 2.0 branch, that uses inline images and has removed all symfony/twig dependancies.

It also has the exception you spoke of #8 

Though it'll be a few more days before I'll be able to look at it again, (barcode looks wrong).

**Comment by hackzilla** [comment]
I've pushed v2.0.

Let me know how you get on.
